services:
  health:
    build:
      context: .
    image: zhou7419/health:latest
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "sqlite:///./database/app.db"
      DEEPSEEK_BASE_URL: "https://api.deepseek.com"
      DEEPSEEK_API_KEY: ""
      SECRET_KEY: ""
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: ""
    volumes:
      - ./database:/app/database
    restart: unless-stopped
